name: Build and Test Pull Requests

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: "Build and Test Pull Requests"
    env:
      NODE_VERSION: '14.x'                # set this to the node version to use      

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Update npm
      run: |
        npm install npm@latest

    - name: Run Unit Tests
      run: |
        npm install        

    