name: Publish Pre-Release Nugets and Docker

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  build:
    name: "Publish Pre-Release Nugets and Docker"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Install NET 9
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: '9.0.x'

    - name: Restore Nuget Packages
      run: dotnet restore MobileConfiguration.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Build Code
      run: dotnet build MobileConfiguration.sln --configuration Release

    - name: 'Get Previous tag'
      id: get-latest-tag
      uses: actions-ecosystem/action-get-latest-tag@v1
      with:
          semver_only: true

    - name: 'Bump Version'
      id: bump-semver
      uses: actions-ecosystem/action-bump-semver@v1
      with:
        current_version: ${{ steps.get-latest-tag.outputs.tag }}
        level: patch
    
    - name: Print Version
      id: next_version
      run: echo ::set-output name=VERSION::${{ steps.bump-semver.outputs.new_version }}.$GITHUB_RUN_NUMBER

    - name: Publish Images to Docker Hub
      run: |
        docker build . --file MobileConfiguration/Dockerfile --tag stuartferguson/mobileconfiguration:master
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push stuartferguson/mobileconfiguration:master

    - name: Publish API
      run: dotnet publish "MobileConfiguration\MobileConfiguration.csproj" --configuration Release --output publishOutput -r win-x64 --self-contained
              -p:Version=${{ steps.next_version.outputs.VERSION }}
              -p:AssemblyVersion=${{ steps.next_version.outputs.VERSION }}
              -p:FileVersion=${{ steps.next_version.outputs.VERSION }}
              -p:InformationalVersion=${{ steps.next_version.outputs.VERSION }}
    
    - name: Build Release Package
      run: |
         cd /home/runner/work/MobileConfiguration/MobileConfiguration/publishOutput
         zip -r ../mobileconfiguration.zip ./*

    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: mobileconfiguration
        path: mobileconfiguration.zip

  deploydevelopment:
    runs-on: developmentserver
    needs: build
    environment: development
    name: "Deploy to Development"
    
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: mobileconfiguration
      
      - name: Remove existing  Windows service
        run: |
          $serviceName = "Transaction Processing - Mobile Configuration"
          # Check if the service exists
          if (Get-Service -Name $serviceName -ErrorAction SilentlyContinue) {
            Stop-Service -Name $serviceName
            sc.exe delete $serviceName
          }

      - name: Unzip the files
        run: |
          Expand-Archive -Path mobileconfiguration.zip -DestinationPath "C:\txnproc\transactionprocessing\mobileconfiguration" -Force
      
      - name: Install as a Windows service
        run: |
          $serviceName = "Transaction Processing - Mobile Configuration"
          $servicePath = "C:\txnproc\transactionprocessing\mobileconfiguration\MobileConfiguration.exe"
                   
          New-Service -Name $serviceName -BinaryPathName $servicePath -Description $serviceName -DisplayName $serviceName -StartupType Automatic
          Start-Service -Name $serviceName         
